CREATE TABLE `agProducts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`barcode` varchar(20) NOT NULL,
	`catalog` varchar(50),
	`itemNo` varchar(50),
	`nameJa` varchar(255) NOT NULL,
	`nameEn` varchar(255),
	`countryOrigin` varchar(60),
	`innerPack` int,
	`piecesPerCarton` int,
	`wholesaleFobJpy` decimal(10,2),
	`cubicMeters` decimal(10,3),
	`grossWeightKg` decimal(10,2),
	`retailPriceTwd` int NOT NULL DEFAULT 22,
	`imageUrl` text,
	`images` json,
	`size` varchar(120),
	`capacity` varchar(120),
	`material` text,
	`assortment` text,
	`status` enum('available','discontinued') NOT NULL DEFAULT 'available',
	`sortOrder` int NOT NULL DEFAULT 0,
	`sourceFile` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agProducts_id` PRIMARY KEY(`id`),
	CONSTRAINT `agProducts_barcode_unique` UNIQUE(`barcode`)
);
