CREATE TABLE `maskPhotos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`maskId` varchar(40) NOT NULL,
	`role` enum('front','back','box','texture','detail') NOT NULL DEFAULT 'front',
	`mimeType` varchar(40) NOT NULL DEFAULT 'image/jpeg',
	`data` longblob NOT NULL,
	`byteSize` int NOT NULL DEFAULT 0,
	`width` int,
	`height` int,
	`sourceFile` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `maskPhotos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maskRuns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`maskId` varchar(40),
	`stage` varchar(40) NOT NULL,
	`status` enum('success','failed','skipped') NOT NULL,
	`attempt` int NOT NULL DEFAULT 1,
	`input` json,
	`output` json,
	`error` text,
	`durationMs` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `maskRuns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maskTasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`workflowKey` varchar(60),
	`title` varchar(200) NOT NULL,
	`detail` text,
	`owner` varchar(60),
	`dueAt` timestamp,
	`status` enum('pending','notified','done','skipped') NOT NULL DEFAULT 'pending',
	`dedupeKey` varchar(160),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `maskTasks_id` PRIMARY KEY(`id`),
	CONSTRAINT `maskTasks_dedupeKey_unique` UNIQUE(`dedupeKey`)
);
--> statement-breakpoint
CREATE TABLE `masks` (
	`id` varchar(40) NOT NULL,
	`sku` varchar(40) NOT NULL,
	`status` enum('draft','analyzed','compliance_blocked','ready','published','archived') NOT NULL DEFAULT 'draft',
	`brand` varchar(120),
	`nameZh` varchar(255) NOT NULL DEFAULT '（待 AI 辨識命名）',
	`nameJa` varchar(255),
	`series` varchar(120),
	`barcode` varchar(20),
	`volumeMl` int,
	`sheetsPerPack` int,
	`piecesPerBox` int,
	`shelfLifeMonths` int,
	`supplierJpy` int,
	`moq` int DEFAULT 12,
	`supplierName` varchar(120),
	`stock` int DEFAULT 30,
	`regulatoryType` enum('general','specific_purpose') NOT NULL DEFAULT 'general',
	`registrationNo` varchar(80),
	`manufactureDate` varchar(60),
	`importerInfo` varchar(255),
	`attributes` json,
	`ingredients` json,
	`websiteCopy` json,
	`wholesaleCopy` json,
	`costBreakdown` json,
	`unitCostTwd` decimal(10,2),
	`wholesaleTwd` int,
	`retailTwd` int,
	`grossMarginPct` decimal(6,2),
	`complianceStatus` enum('pending','pass','warn','blocked') NOT NULL DEFAULT 'pending',
	`complianceReport` json,
	`productId` int,
	`sourceFolder` varchar(255),
	`sourceFiles` json,
	`note` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `masks_id` PRIMARY KEY(`id`),
	CONSTRAINT `masks_sku_unique` UNIQUE(`sku`)
);
