import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'cn' | 'en' | 'ja';

const STORAGE_KEY = 'rokaizumi.lang';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  zh: {
    // Header
    'nav.home': '首頁',
    'nav.products': '產品',
    'nav.videos': '影片',
    'nav.cart': '購物車',
    
    // Home page
    'home.company': 'ろかいずみ合同会社',
    'home.title': '銀髮生活品質加乘輔具 · 日本精美小商品',
    'home.subtitle': '日本直送出口，服務台灣與澳洲市場',
    'home.browseProducts': '瀏覽產品',
    'home.japanConnection': '日本商品即時連線',
    'home.whyChooseUs': '為什麼選擇我們',
    'home.directFromJapan': '日本直採',
    'home.directFromJapanDesc': '直接從日本採購，確保產品品質和價格優勢。',
    'home.globalExport': '全球出口',
    'home.globalExportDesc': '日本直送出口，服務台灣與澳洲市場。',
    'home.professionalService': '專業服務',
    'home.professionalServiceDesc': '提供日本精美小商品和銀髮生活品質加乘輔具的專業資詢。',
    'home.latestVideos': '最新採購影片',
    'home.viewAll': '查看全部',
    'home.productCategories': '主要產品類別',
    'home.hundredYenProducts': '日本精美小商品',
    'home.hundredYenProductsDesc': '精選日本優質小商品',
    'home.careEquipment': '銀髮生活品質加乘輔具',
    'home.careEquipmentDesc': '專業銀髮生活輔具，提升生活品質',
    
    // Products page
    'products.filter': '篩選器',
    'products.reset': '重置',
    'products.mainCategory': '主要分類',
    'products.allProducts': '全部商品',
    'products.hundredYen': '🛍️ 日本精美小商品',
    'products.care': '♿ 銀髮生活品質加乘輔具',
    'products.subCategory': '細分類別',
    'products.priceRange': '價格範圍',
    'products.status': '商品狀態',
    'products.available': '可售',
    'products.reserved': '預訂',
    'products.sold': '已售',
    'products.found': '找到',
    'products.items': '件商品',
    'products.viewDetails': '查看詳情',
    'products.addToCart': '加入購物車',
    'products.noProducts': '沒有找到符合條件的商品',
    'products.back': '返回首頁',
    'products.tryAdjust': '請嘗試調整篩選條件',
    'products.hundredYenTitle': '🛍️ 日本精美小商品',
    'products.hundredYenDesc': '精選日本優質小商品，物美價廉',
    'products.careTitle': '♿ 銀髮生活品質加乘輔具',
    'products.careDesc': '專業銀髮生活輔具，提升生活品質',
    'products.allProductsDesc': '瀏覽我們所有的優質商品',
    'products.filters': '篩選器',
    'products.showing': '顯示',
    'products.products': '個產品',
    'products.resetFilters': '重置篩選器',
    'home.category1': '日本精美小商品',
    'home.category2': '銀髮生活品質加乘輔具',

    // AG fixed-price catalog
    'ag.badge': '山田化學生活選品',
    'ag.titlePrefix': '實用日本生活小物，',
    'ag.fixedPrice': '單件 NT$22',
    'ag.subtitle': '本頁商品採固定售價，已停售品項不會顯示。可用商品名稱、型號或條碼快速搜尋。',
    'ag.searchLabel': '搜尋山田化學商品',
    'ag.searchPlaceholder': '搜尋名稱、型號或條碼',
    'ag.countPrefix': '共',
    'ag.countSuffix': '件商品',
    'ag.imagePending': '圖片整理中',
    'ag.viewOfficial': '查看官方資料',
    'ag.model': '型號',
    'ag.listPrice': '定價',
    'ag.officialData': '官網資料',
    'ag.officialInfo': '官方資訊',
    'ag.lineInquiry': 'LINE 詢問',
    'ag.noResults': '找不到符合條件的商品。',
    'ag.loading': '商品資料載入中，請稍候。',
    'ag.pagination': '商品分頁',
    'ag.previous': '上一頁',
    'ag.next': '下一頁',
    'ag.spec.officialNumber': '官方品番',
    'ag.spec.jan': 'JAN 條碼',
    'ag.spec.size': '商品尺寸',
    'ag.spec.capacity': '容量',
    'ag.spec.material': '材質',
    'ag.spec.assortment': '顏色／組合',
    'ag.spec.origin': '產地',
    'ag.spec.quantity': '官網包裝數量',
    'ag.spec.packageSize': '包裝尺寸',
    'ag.spec.caseSize': '外箱尺寸',
    'ag.close': '關閉官方商品資訊',
    'ag.officialProductData': '山田化學官方商品資料',
    'ag.noOfficialImage': '官網目前沒有對應圖片',
    'ag.brand': '山田化學',
    'ag.sitePrice': '本站定價',
    'ag.introduction': '商品介紹',
    'ag.unmatched': '這件商品尚未在目前的官方目錄中對到完整規格，請以 JAN 條碼向客服查詢。',
    'ag.lineInquiryProduct': 'LINE 詢問此商品',
    'ag.disclaimer': '商品規格整理自山田化學官方目錄；最新內容仍以原廠資料為準。本站不顯示原廠批發報價。',

    // Shared site header
    'header.subtitle': '日本介護用品專賣',
    'header.searchPlaceholder': '搜尋商品...',
    'header.agProducts': '22元商品',
    'header.daiko': '代購',
    'header.b2b': '企業合作',
    'header.admin': '後台',
    'header.logout': '登出',
    
    // Cart
    'cart.title': '購物車',
    'cart.empty': '購物車是空的',
    'cart.startShopping': '開始購物',
    'cart.subtotal': '小計',
    'cart.total': '總計',
    'cart.checkout': '結帳',
    'cart.continueShopping': '繼續購物',
    'cart.remove': '移除',
    'cart.quantity': '數量',
    
    // Categories
    'category.dailyGoods': '日用百貨',
    'category.kitchen': '廚房用品',
    'category.stationery': '文具用品',
    'category.cleaning': '清潔用品',
    'category.storage': '收納用品',
    'category.beauty': '美妝保養',
    'category.snacks': '食品零食',
    'category.toys': '玩具雜貨',
    'category.mobility': '行動輔助',
    'category.bathroom': '衛浴安全',
    'category.health': '健康監測',
    'category.nursing': '護理用品',
    'category.rehabilitation': '復健器材',
    'category.livingAids': '生活輔具',
    'category.bedside': '床邊照護',
    'category.safety': '安全監控',
      'cart.addSuccess': '已加入購物車',
    'nav.login': '登入',
    'products.categories': '分類',
},
  en: {
    // Header
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.videos': 'Videos',
    'nav.cart': 'Cart',
    
    // Home page
    'home.company': 'Rokaizumi LLC',
    'home.title': 'Japanese 100-Yen Products · Elderly Care Equipment',
    'home.subtitle': 'Professional Export Worldwide, Including Taiwan',
    'home.browseProducts': 'Browse Products',
    'home.japanConnection': 'Japan Live Connection',
    'home.category1': 'Japanese 100-Yen Products',
    'home.category2': 'Elderly Care Equipment',
    
    // Products page
    'products.allProducts': 'All Products',
    'products.allProductsDesc': 'Browse all our quality products',
    'products.filters': 'Filters',
    'products.showing': 'Showing',
    'products.products': 'products',
    'products.resetFilters': 'Reset Filters',
    'products.noProducts': 'No products found',
    'products.back': 'Back to Home',
    'products.viewDetails': 'View Details',
    'products.available': 'Available',
    'products.reserved': 'Reserved',
    'products.sold': 'Sold',
      'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.startShopping': 'Start Shopping',
    'cart.subtotal': 'Subtotal',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.continueShopping': 'Continue Shopping',
    'cart.remove': 'Remove',
    'cart.quantity': 'Quantity',
    'cart.addSuccess': 'Added to cart',
    'category.dailyGoods': 'Daily Necessities',
    'category.kitchen': 'Kitchen Items',
    'category.storage': 'Storage',
    'category.stationery': 'Stationery',
    'category.cleaning': 'Cleaning Supplies',
    'category.toys': 'Toys',
    'category.beauty': 'Beauty Products',
    'category.snacks': 'Food & Snacks',
    'category.health': 'Health Monitoring',
    'category.mobility': 'Mobility Aids',
    'category.bathroom': 'Bathroom Safety',
    'category.nursing': 'Nursing Supplies',
    'category.livingAids': 'Daily Living Aids',
    'category.rehabilitation': 'Rehabilitation',
    'category.bedside': 'Bedside Care',
    'category.safety': 'Safety Monitoring',
    'home.whyChooseUs': 'Why Choose Us',
    'home.directFromJapan': 'Direct from Japan',
    'home.directFromJapanDesc': 'Shipped directly from Osaka, Japan',
    'home.globalExport': 'Global Export',
    'home.globalExportDesc': 'Professional export worldwide',
    'home.professionalService': 'Professional Service',
    'home.professionalServiceDesc': 'Full Chinese-language customer support',
    'home.productCategories': 'Product Categories',
    'home.hundredYenProducts': 'Japanese 100-Yen Products',
    'home.hundredYenProductsDesc': 'Carefully selected Japanese daily goods, kitchenware and stationery',
    'home.careEquipment': 'Elderly Care Equipment',
    'home.careEquipmentDesc': 'Japanese care products, mobility aids and health monitoring',
    'home.latestVideos': 'Latest Videos',
    'home.viewAll': 'View All',
    'products.addToCart': 'Add to Cart',
    'products.categories': 'Categories',
    'products.filter': 'Filter',
    'products.reset': 'Reset',
    'products.found': 'found',
    'products.items': 'items',
    'products.mainCategory': 'Main Category',
    'products.subCategory': 'Subcategory',
    'products.priceRange': 'Price Range',
    'products.status': 'Status',
    'products.tryAdjust': 'Try adjusting your filters',
    'products.hundredYen': '100-Yen Products',
    'products.hundredYenTitle': 'Japanese 100-Yen Products',
    'products.hundredYenDesc': 'Carefully selected Japanese daily goods',
    'products.care': 'Care Equipment',
    'products.careTitle': 'Elderly Care Equipment',
    'products.careDesc': 'Japanese care products and mobility aids',

    // AG fixed-price catalog
    'ag.badge': 'Yamada Kagaku Collection',
    'ag.titlePrefix': 'Practical Japanese everyday goods, ',
    'ag.fixedPrice': 'NT$22 each',
    'ag.subtitle': 'All products on this page have a fixed price. Discontinued items are hidden. Search by product name, model number, or JAN code.',
    'ag.searchLabel': 'Search Yamada Kagaku products',
    'ag.searchPlaceholder': 'Search name, model, or JAN code',
    'ag.countPrefix': 'Showing',
    'ag.countSuffix': 'items',
    'ag.imagePending': 'Image coming soon',
    'ag.viewOfficial': 'View official details',
    'ag.model': 'Model',
    'ag.listPrice': 'Price',
    'ag.officialData': 'Official data',
    'ag.officialInfo': 'Product details',
    'ag.lineInquiry': 'Ask on LINE',
    'ag.noResults': 'No matching products found.',
    'ag.loading': 'Loading product data…',
    'ag.pagination': 'Product pages',
    'ag.previous': 'Previous',
    'ag.next': 'Next',
    'ag.spec.officialNumber': 'Official item no.',
    'ag.spec.jan': 'JAN code',
    'ag.spec.size': 'Product size',
    'ag.spec.capacity': 'Capacity',
    'ag.spec.material': 'Material',
    'ag.spec.assortment': 'Color / assortment',
    'ag.spec.origin': 'Country of origin',
    'ag.spec.quantity': 'Official pack quantity',
    'ag.spec.packageSize': 'Package size',
    'ag.spec.caseSize': 'Case size',
    'ag.close': 'Close product details',
    'ag.officialProductData': 'Yamada Kagaku official product data',
    'ag.noOfficialImage': 'No matching official image',
    'ag.brand': 'Yamada Kagaku',
    'ag.sitePrice': 'Our price',
    'ag.introduction': 'Product introduction',
    'ag.unmatched': 'Full specifications were not found in the current official catalog. Please contact us with the JAN code.',
    'ag.lineInquiryProduct': 'Ask about this product on LINE',
    'ag.disclaimer': 'Product specifications are based on Yamada Kagaku’s official catalog. Refer to the manufacturer’s data for the latest information. Wholesale prices are not shown on this site.',

    // Shared site header
    'header.subtitle': 'Japanese Care Products',
    'header.searchPlaceholder': 'Search products...',
    'header.agProducts': 'NT$22 Items',
    'header.daiko': 'Proxy Shopping',
    'header.b2b': 'Business',
    'header.admin': 'Admin',
    'header.logout': 'Log out',
    'nav.login': 'Login',
},
  ja: {
    // Header
    'nav.home': 'ホーム',
    'nav.products': '商品',
    'nav.videos': '動画',
    'nav.cart': 'カート',
    
    // Home page
    'home.company': 'ろかいずみ合同会社',
    'home.title': '日本百円商品・高齢者介護用品',
    'home.subtitle': '世界中（台湾を含む）への専門輸出',
    'home.browseProducts': '商品を見る',
    'home.japanConnection': '日本商品リアルタイム接続',
    'home.whyChooseUs': '選ばれる理由',
    'home.directFromJapan': '日本直採',
    'home.directFromJapanDesc': '日本から直接調達、品質と価格の優位性を保証。',
    'home.globalExport': 'グローバル輸出',
    'home.globalExportDesc': '日本の優良商品を台湾を含む世界中へお届けする専門輸出サービス。',
    'home.professionalService': '専門サービス',
    'home.professionalServiceDesc': '日本百円商品と高齢者介護用品の専門コンサルティング。',
    'home.latestVideos': '最新調達動画',
    'home.viewAll': 'すべて見る',
    'home.productCategories': '主要商品カテゴリ',
    'home.hundredYenProducts': '日本百円商品',
    'home.hundredYenProductsDesc': '日本百円ショップの優良商品を厳選',
    'home.careEquipment': '高齢者介護用品',
    'home.careEquipmentDesc': '生活の質を向上させる専門介護用品',
    
    // Products page
    'products.filter': 'フィルター',
    'products.reset': 'リセット',
    'products.mainCategory': 'メインカテゴリ',
    'products.allProducts': 'すべての商品',
    'products.hundredYen': '🛍️ 日本百円商品',
    'products.care': '♿ 高齢者介護用品',
    'products.subCategory': 'サブカテゴリ',
    'products.priceRange': '価格帯',
    'products.status': '商品状態',
    'products.available': '販売中',
    'products.reserved': '予約済',
    'products.sold': '売切',
    'products.found': '見つかりました',
    'products.items': '件',
    'products.viewDetails': '詳細を見る',
    'products.addToCart': 'カートに追加',
    'products.noProducts': '商品が見つかりません',
    'products.back': 'ホームに戻る',
    'products.tryAdjust': 'フィルターを調整してください',
    'products.hundredYenTitle': '🛍️ 日本百円商品',
    'products.hundredYenDesc': '日本百円ショップの優良商品をお手頃価格で',
    'products.careTitle': '♿ 高齢者介護用品',
    'products.careDesc': '生活の質を向上させる専門介護用品',
    'products.allProductsDesc': 'すべての優良商品を閲覧',
    'products.filters': 'フィルター',
    'products.showing': '表示中',
    'products.products': '件の商品',
    'products.resetFilters': 'フィルターをリセット',
    'home.category1': '日本百円商品',
    'home.category2': '高齢者介護用品',

    // AG fixed-price catalog
    'ag.badge': '山田化学の生活用品',
    'ag.titlePrefix': '便利な日本の生活雑貨、',
    'ag.fixedPrice': '1点 NT$22',
    'ag.subtitle': '当ページの商品は一律価格です。販売終了商品は表示されません。商品名・品番・JANコードで検索できます。',
    'ag.searchLabel': '山田化学の商品を検索',
    'ag.searchPlaceholder': '商品名・品番・JANコードで検索',
    'ag.countPrefix': '全',
    'ag.countSuffix': '点',
    'ag.imagePending': '画像準備中',
    'ag.viewOfficial': '公式情報を見る',
    'ag.model': '品番',
    'ag.listPrice': '販売価格',
    'ag.officialData': '公式情報',
    'ag.officialInfo': '商品情報',
    'ag.lineInquiry': 'LINEで問い合わせ',
    'ag.noResults': '条件に一致する商品が見つかりません。',
    'ag.loading': '商品データを読み込んでいます。',
    'ag.pagination': '商品ページ',
    'ag.previous': '前へ',
    'ag.next': '次へ',
    'ag.spec.officialNumber': '公式品番',
    'ag.spec.jan': 'JANコード',
    'ag.spec.size': '商品サイズ',
    'ag.spec.capacity': '容量',
    'ag.spec.material': '材質',
    'ag.spec.assortment': 'カラー／組合せ',
    'ag.spec.origin': '原産国',
    'ag.spec.quantity': '公式梱包数量',
    'ag.spec.packageSize': 'パッケージサイズ',
    'ag.spec.caseSize': 'ケースサイズ',
    'ag.close': '公式商品情報を閉じる',
    'ag.officialProductData': '山田化学 公式商品情報',
    'ag.noOfficialImage': '公式画像は現在ありません',
    'ag.brand': '山田化学',
    'ag.sitePrice': '当サイト価格',
    'ag.introduction': '商品紹介',
    'ag.unmatched': '現在の公式カタログで詳細情報を確認できません。JANコードを添えてお問い合わせください。',
    'ag.lineInquiryProduct': 'LINEでこの商品を問い合わせ',
    'ag.disclaimer': '商品仕様は山田化学の公式カタログをもとに掲載しています。最新情報はメーカー資料をご確認ください。卸価格は当サイトには表示していません。',

    // Shared site header
    'header.subtitle': '日本介護用品専門店',
    'header.searchPlaceholder': '商品を検索...',
    'header.agProducts': 'NT$22商品',
    'header.daiko': '購入代行',
    'header.b2b': '法人のお客様',
    'header.admin': '管理画面',
    'header.logout': 'ログアウト',
    
    // Cart
    'cart.title': 'ショッピングカート',
    'cart.empty': 'カートは空です',
    'cart.startShopping': '買い物を始める',
    'cart.subtotal': '小計',
    'cart.total': '合計',
    'cart.checkout': '購入手続き',
    'cart.continueShopping': '買い物を続ける',
    'cart.remove': '削除',
    'cart.quantity': '数量',
    
    // Categories
    'category.dailyGoods': '日用品',
    'category.kitchen': 'キッチン用品',
    'category.stationery': '文具',
    'category.cleaning': '清掃用品',
    'category.storage': '収納用品',
    'category.beauty': '美容用品',
    'category.snacks': '食品・お菓子',
    'category.toys': 'おもちゃ・雑貨',
    'category.mobility': '移動補助',
    'category.bathroom': '浴室安全',
    'category.health': '健康監視',
    'category.nursing': '介護用品',
    'category.rehabilitation': 'リハビリ用品',
    'category.livingAids': '生活補助具',
    'category.bedside': 'ベッドサイドケア',
    'category.safety': '安全監視',
      'cart.addSuccess': 'カートに追加しました',
    'nav.login': 'ログイン',
    'products.categories': 'カテゴリー',
},
  cn: {
    // Header
    'nav.home': '首页',
    'nav.products': '产品',
    'nav.videos': '视频',
    'nav.cart': '购物车',
    
    // Home page
    'home.company': 'ろかいずみ合同会社',
    'home.title': '银发生活品质加乘辅具 · 日本精美小商品',
    'home.subtitle': '日本直送出口，服务台湾与澳洲市场',
    'home.browseProducts': '浏览产品',
    'home.japanConnection': '日本商品即时连接',
    'home.whyChooseUs': '为什么选择我们',
    'home.directFromJapan': '日本直采',
    'home.directFromJapanDesc': '直接从日本采购，确保产品品质和价格优势。',
    'home.globalExport': '全球出口',
    'home.globalExportDesc': '日本直送出口，服务台湾与澳洲市场。',
    'home.professionalService': '专业服务',
    'home.professionalServiceDesc': '提供日本精美小商品和银发生活品质加乘辅具的专业资询。',
    'home.latestVideos': '最新采购视频',
    'home.viewAll': '查看全部',
    'home.productCategories': '主要产品类别',
    'home.hundredYenProducts': '日本精美小商品',
    'home.hundredYenProductsDesc': '精选日本优质小商品',
    'home.careEquipment': '银发生活品质加乘辅具',
    'home.careEquipmentDesc': '专业银发生活辅具，提升生活品质',
    
    // Products page
    'products.filter': '筛选器',
    'products.reset': '重置',
    'products.mainCategory': '主要分类',
    'products.allProducts': '全部商品',
    'products.hundredYen': '🛍️ 日本精美小商品',
    'products.care': '♿ 银发生活品质加乘辅具',
    'products.subCategory': '细分类别',
    'products.priceRange': '价格范围',
    'products.status': '商品状态',
    'products.available': '可售',
    'products.reserved': '预订',
    'products.sold': '已售',
    'products.found': '找到',
    'products.items': '件商品',
    'products.viewDetails': '查看详情',
    'products.addToCart': '加入购物车',
    'products.noProducts': '没有找到符合条件的商品',
    'products.back': '返回首页',
    'products.tryAdjust': '请尝试调整筛选条件',
    'products.hundredYenTitle': '🛍️ 日本精美小商品',
    'products.hundredYenDesc': '精选日本优质小商品，物美价廉',
    'products.careTitle': '♿ 银发生活品质加乘辅具',
    'products.careDesc': '专业银发生活辅具，提升生活品质',
    'products.allProductsDesc': '浏览我们所有的优质商品',
    'products.filters': '筛选器',
    'products.showing': '显示',
    'products.products': '个产品',
    'products.resetFilters': '重置筛选器',
    'home.category1': '日本精美小商品',
    'home.category2': '银发生活品质加乘辅具',

    // AG fixed-price catalog
    'ag.badge': '山田化学生活选品',
    'ag.titlePrefix': '实用日本生活小物，',
    'ag.fixedPrice': '单件 NT$22',
    'ag.subtitle': '本页商品采用固定售价，已停售商品不会显示。可用商品名称、型号或条码快速搜索。',
    'ag.searchLabel': '搜索山田化学商品',
    'ag.searchPlaceholder': '搜索名称、型号或条码',
    'ag.countPrefix': '共',
    'ag.countSuffix': '件商品',
    'ag.imagePending': '图片整理中',
    'ag.viewOfficial': '查看官方资料',
    'ag.model': '型号',
    'ag.listPrice': '定价',
    'ag.officialData': '官网资料',
    'ag.officialInfo': '官方信息',
    'ag.lineInquiry': 'LINE 咨询',
    'ag.noResults': '找不到符合条件的商品。',
    'ag.loading': '商品数据加载中，请稍候。',
    'ag.pagination': '商品分页',
    'ag.previous': '上一页',
    'ag.next': '下一页',
    'ag.spec.officialNumber': '官方品号',
    'ag.spec.jan': 'JAN 条码',
    'ag.spec.size': '商品尺寸',
    'ag.spec.capacity': '容量',
    'ag.spec.material': '材质',
    'ag.spec.assortment': '颜色／组合',
    'ag.spec.origin': '产地',
    'ag.spec.quantity': '官网包装数量',
    'ag.spec.packageSize': '包装尺寸',
    'ag.spec.caseSize': '外箱尺寸',
    'ag.close': '关闭官方商品信息',
    'ag.officialProductData': '山田化学官方商品资料',
    'ag.noOfficialImage': '官网目前没有对应图片',
    'ag.brand': '山田化学',
    'ag.sitePrice': '本站定价',
    'ag.introduction': '商品介绍',
    'ag.unmatched': '这件商品尚未在目前的官方目录中匹配到完整规格，请向客服提供 JAN 条码查询。',
    'ag.lineInquiryProduct': 'LINE 咨询此商品',
    'ag.disclaimer': '商品规格整理自山田化学官方目录；最新内容仍以原厂资料为准。本站不显示原厂批发报价。',

    // Shared site header
    'header.subtitle': '日本介护用品专卖',
    'header.searchPlaceholder': '搜索商品...',
    'header.agProducts': '22元商品',
    'header.daiko': '代购',
    'header.b2b': '企业合作',
    'header.admin': '后台',
    'header.logout': '退出登录',
    
    // Cart
    'cart.title': '购物车',
    'cart.empty': '购物车是空的',
    'cart.startShopping': '开始购物',
    'cart.subtotal': '小计',
    'cart.total': '总计',
    'cart.checkout': '结帐',
    'cart.continueShopping': '继续购物',
    'cart.remove': '移除',
    'cart.quantity': '数量',
    
    // Categories
    'category.dailyGoods': '日用百货',
    'category.kitchen': '厨房用品',
    'category.stationery': '文具用品',
    'category.cleaning': '清洁用品',
    'category.storage': '收纳用品',
    'category.beauty': '美妆保养',
    'category.snacks': '食品零食',
    'category.toys': '玩具杂货',
    'category.mobility': '行动辅助',
    'category.bathroom': '卫浴安全',
    'category.health': '健康监测',
    'category.nursing': '护理用品',
    'category.rehabilitation': '复健器材',
    'category.livingAids': '生活辅具',
    'category.bedside': '床边照护',
    'category.safety': '安全监控',
      'cart.addSuccess': '已加入购物车',
    'nav.login': '登录',
    'products.categories': '分类',
},
};

/** 讀取上次選擇的語言；沒有的話用繁中（本站主要客群在台灣） */
function initialLanguage(): Language {
  if (typeof window === 'undefined') return 'zh';
  const saved = window.localStorage.getItem(STORAGE_KEY);
  if (saved && saved in translations) return saved as Language;
  return 'zh';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(initialLanguage);

  // 語言選擇要跨頁面保留，否則每次換頁都會跳回預設值
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      window.localStorage.setItem(STORAGE_KEY, lang);
    } catch {
      /* 隱私模式下忽略 */
    }
  };

  // 遞補鏈：選定語言 → 繁中 → key 本身。
  // 直接吐 key（例如畫面上出現 "cart.addSuccess"）對使用者毫無意義，
  // 所以缺翻譯時寧可顯示繁中。
  const t = (key: string): string => {
    const table = translations[language] as Record<string, string> | undefined;
    return table?.[key] ?? (translations.zh as Record<string, string>)[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
